### PR TITLE
Storage get count

### PR DESCRIPTION
**Pull request by johnconnor77**
Check the functions get and count for db storage and file storage

### CODE REVIEW

**Review by jormao — CHANGES_REQUESTED** [review]
line 94 is too long, please review pep8 in your file

**Comment by johnconnor77** [comment]
I've alrady done the changes

**Review by pafuentess — CHANGES_REQUESTED** [review]
what happens if the function get receives a string.

**Review by pafuentess — APPROVED** [review]

**Review by jormao — APPROVED** [review]
OK

**Pull request merged**
